/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./index.html",
    "./js/**/*.js",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "tertiary-fixed-dim": "#ffb95a",
        "surface-bright": "#f9f9f9",
        "secondary-fixed-dim": "#ffb77d",
        "on-primary-fixed": "#002201",
        surface: "#f9f9f9",
        outline: "#6f7a6a",
        "tertiary-container": "#a26800",
        secondary: "#914d00",
        "primary-container": "#518048",
        "outline-variant": "#becab7",
        "on-background": "#1a1c1c",
        "on-surface": "#1a1c1c",
        "surface-dim": "#dadada",
        "on-tertiary": "#ffffff",
        "surface-container-low": "#f3f3f3",
        primary: "#396632",
        "on-tertiary-fixed-variant": "#643f00",
        "on-primary": "#ffffff",
        "on-primary-container": "#f8fff0",
        "primary-fixed-dim": "#a1d494",
        "surface-container-high": "#e8e8e8",
        "error-container": "#ffdad6",
        "surface-tint": "#3b6934",
        "surface-container": "#eeeeee",
        "on-secondary-fixed": "#2f1500",
        "on-error": "#ffffff",
        "on-secondary": "#ffffff",
        "on-surface-variant": "#3f4a3b",
        background: "#f9f9f9",
        "surface-container-lowest": "#ffffff",
        "inverse-surface": "#2f3131",
        "on-primary-fixed-variant": "#23501e",
        "secondary-fixed": "#ffdcc3",
        "secondary-container": "#fc9430",
        "inverse-primary": "#a1d494",
        "on-tertiary-fixed": "#2a1800",
        "on-tertiary-container": "#fffbff",
        "surface-container-highest": "#e2e2e2",
        "inverse-on-surface": "#f0f1f1",
        "primary-fixed": "#bcf0ae",
        "on-secondary-fixed-variant": "#6e3900",
        "tertiary-fixed": "#ffddb6",
        "surface-variant": "#e2e2e2",
        error: "#ba1a1a",
        "on-secondary-container": "#663500",
        tertiary: "#815200",
        "on-error-container": "#93000a",
      },
      borderRadius: {
        DEFAULT: "1rem",
        lg: "2rem",
        xl: "3rem",
        full: "9999px",
      },
      fontFamily: {
        headline: ["Plus Jakarta Sans"],
        body: ["Inter"],
        label: ["Inter"],
      },
    },
  },
  plugins: [
    require("@tailwindcss/forms"),
    require("@tailwindcss/container-queries"),
  ],
};
